### ISSUE TITLE
workspace has a reference to a missing target with GUID 'PACKAGE-TARGET:libcurl'

### ISSUE THREAD

**Issue by samuelail** [SideStore/iMobileDevice.swift#2]
Installed this package because it looked really promising but got this error when I tried building the app:

Unable to resolve build file: BuildFile<PACKAGE-TARGET:libfragmentzip--7CE7E1B83B58C914-dynamic::BUILDPHASE_1::0> (The workspace has a reference to a missing target with GUID 'PACKAGE-TARGET:libcurl')

**Comment by JoeMatt** [comment]
You can probably just delete the worskpace and let xcode regenerate it. I'll fix the repo when I get a chance, thanks for reporting.
